name: Validate project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  norm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Pass norminette
        run: make norm

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile
        run: make
