name: Validate project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  norm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4

      - name: Pass norminette
        run: make norm

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build MiniLibX
        env:
          MLX_DIR: minilibx-linux
        run: |
          if [ -d "$MLX_DIR" ]; then
            make -C "$MLX_DIR"
          else
            echo "MiniLibX directory not found: $MLX_DIR"
            exit 1
          fi

      - name: Compile
        run: make

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Pass tests
        run: make test
