name: Validate project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  norm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4

      - name: Pass norminette
        run: make norm

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: "Compile submodules"
        run: make buildsubmodules

      - name: Compile
        run: make

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:main

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Compile submodules"
        run: make buildsubmodules

      - name: Pass tests
        run: make test
